### ISSUE TITLE
Build order

### ISSUE THREAD

**Issue by jrson83** [hairyf/ptsup#3]
Having just a single `tsconfig.json` inside a monorepo root, without references or paths set up, using `ptsup` and running `build` recursively, how does `ptsup` know/detect the correct package build order?

**Comment by hairyf** [comment]
esbuild determines the use of tsconfig.json, which is normally located in the current execution path and is searched backwards. This works properly in a Windows environment. The configuration for outputting dts is controlled by the internal compilerOptions option.

```ts
  const compilerOptions = {
    allowJs: true,
    declaration: true,
    incremental: true,
    skipLibCheck: true,
    emitDeclarationOnly: true,
    outDir: options.outdir,
  }
  const tsHost = ts.createCompilerHost!(compilerOptions)
  const program = ts.createProgram!(inputs, compilerOptions, tsHost)
  await program.emit()
```

**Comment by jrson83** [comment]
Thank you for the info.
