### ISSUE TITLE
`internal` option not respected

### ISSUE THREAD

**Issue by jrson83** [hairyf/ptsup#4]
`ptsup` does not respect `internal` when set. The following command does not inline the `react` dep in bundle:

```bash
ptsup --entry=src/index.ts --clean --internal=react
```

When providing an empty array `--external=[]` as external, it does inline the dep as expected in the bundle:

```bash
ptsup --entry=src/index.ts --clean --external=[] --internal=react
```

### Replicate 

1. Clone the repo, switch branch, install & build:
```bash
git clone https://github.com/jrson83/node-ts-preset
cd node-ts-preset
git checkout ptsup

pnpm install
pnpm build
```

> It builds and inlines the `react` dep.

2. Remove from `package.json` `build` script:

```bash
--external=[]
```

3. run `pnpm build`.

> It does not inline the `react` dep.

**Comment by jrson83** [comment]
@hairyf Could you please correct me if I'm using ptsup wrong? I would be pleased if you answer since ptsup is a great tool you made!

The docs are missing info on how to use `internal` and `external`.
Also a statement on how ptsup bundles imported modules by default would be great.

I expect that `devDependencies` which are imported are bundled automatically by default. But when adding `react` to  the `devDependencies` or `dependencies` it does not get bundled unless I specify `--external --internal=react`.
So the `--internal` only gets bundled when `--external` is `true` or an `array`. Is this the expected behaviour?

**Comment by hairyf** [comment]
```ts
export const externalize = (internal?: string[]): Plugin => {
  return {
    name: 'externalize-deps',
    setup: ({ onResolve }) => {
      onResolve({ filter: /.*/ }, (args) => {
        if (args.path[0] !== '.' && !path.isAbsolute(args.path) && !internal?.includes(args.path))
          return { external: true }
      })
    },
  }
}
```

Internally, there is an esbuild plugin that automatically converts modules to external when they are not absolute paths and have not been added to internal. This ensures that dependencies used in the bundling process are not compiled. Ptsup is a tool specifically designed to compile third-party libraries, and it should handle both dependencies and devDependencies.

Therefore, if you want this dependency to be bundled, you need to add the `--internal` option. If it does not work after adding the option, it may be an issue with the ptsup program. Thank you for bringing this to my attention, and I will fix the issue as soon as possible.

**Comment by jrson83** [comment]
Either `defaultConfig: PtsupConfiguration` should include `externals: []`, or the condition from `config-resolve.ts` should be fixed. Thank you.
